apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 2048-game-app
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: infrastructure/kubernetes
    repoURL: 'https://github.com/feriva22/docker-2048.git'
    targetRevision: HEAD
  sources: []
  project: default