apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: game-2048
  name: game-2048
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - image: feriva22/docker-2048:latest
        imagePullPolicy: IfNotPresent
        name: game-2048
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: game-2048
  name: game-2048
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: game-2048
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay-ingress-game-2048
  namespace: default
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: game-2048.deploy-at.my.id
    http:
      paths:
      - backend:
          service:
            name: game-2048
            port:
              number: 80
        path: /
        pathType: Prefix