apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: 2048-game
  name: 2048-game
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048-game
  template:
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - image: feriva22/docker-2048:latest
        imagePullPolicy: IfNotPresent
        name: 2048-game
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: 2048-game
  name: 2048-game
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: 2048-game
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: relay-ingress-2048-game
  namespace: default
spec:
  ingressClassName: cloudflare-tunnel
  rules:
  - host: 2048-game.deploy-at.my.id
    http:
      paths:
      - backend:
          service:
            name: 2048-game
            port:
              number: 80
        path: /
        pathType: Prefix